name: leetcode_dart
description: LeetCode problems solved in Dart
version: 1.0.0

environment:
  sdk: '>=2.14.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0 
dependencies:
  intl: ^0.20.2
